%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/mathiaschristiansen/Projects/pan_tilt/control-sys/data/processed/tilt_updown.csv
%
% Auto-generated by MATLAB on 07-May-2024 16:39:39

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Axis", "Voltage", "Angle", "Time"];
opts.VariableTypes = ["categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Axis", "EmptyFieldRule", "auto");

% Import the data
tiltupdown = readtable("/Users/mathiaschristiansen/Projects/pan_tilt/control-sys/data/processed/tilt_updown.csv", opts);

in = table2array(tiltupdown(:,"Voltage"));
out = table2array(tiltupdown(:,"Angle"));

%% Clear temporary variables
clear opts